### ISSUE TITLE
Failed to initialize type System MarkupString even when property is ignored.

### ISSUE THREAD

**Issue by groogiam** [mganss/ExcelMapper#195]
One of the objects I am attempting to read in has a property.

```csharp
public Func<dynamic, MarkupString> CustomOutput { get; set; }
```

I have ExcelMapper configured to ignore this property 
```csharp
var mapper = new ExcelMapper(xlsxFilePath);
mapper.Ignore<EntitySummaryProperty>(i => i.CustomOutput);
```

but it still throws this error. but it still throws this exception.

```
Failed to initialize type System.Func`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.AspNetCore.Components.MarkupString, Microsoft.AspNetCore.Components, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].
```

Stack Trace

```
at Ganss.Excel.ExcelMapper.MapCells(Type type, Func`3 valueParser, TypeMapper typeMapper, IEnumerable`1 cells, Int32& objInstanceIdx, IRow row, ISet`1 callChain)
   at Ganss.Excel.ExcelMapper.MapCells(Type type, Func`3 valueParser, TypeMapper typeMapper, IEnumerable`1 cells, Int32& objInstanceIdx, IRow row, ISet`1 callChain)
   at Ganss.Excel.ExcelMapper.Fetch(ISheet sheet, Type type, Func`3 valueParser)+MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at UserQuery.Main(), line 18
```

Inner Exceptions

![image](https://user-images.githubusercontent.com/1992395/174806700-64498c05-ef79-4610-8e6d-4b1d44ea9019.png)

I have not look to at the code for this but it seems like some processing is happening for ignored properties that could probably be short circuited if the event the property is ignored. Thanks for your help.

**Comment by mganss** [comment]
I can't repro. Can you provide a minimal example including an Excel file that demonstrates the issue? Thanks.

**Comment by mganss** [comment]
This was due to a comparison of `PropertyInfo` objects using `==` which resulted in the issue described at https://github.com/dotnet/runtime/issues/16288.

Since we're multi-targeting I went with comparing `MetadataToken` to solve this for now.

**Comment by groogiam** [comment]
Very interesting. Thanks for the details on the quick turn around on a fix.
