### ISSUE TITLE
Unable to convert "2958465" to System.DateTime.

### ISSUE THREAD

**Issue by miniquery** [mganss/ExcelMapper#227]
I've got the following error when trying to parse date 31/12/9999:
```
Ganss.Excel.Exceptions.ExcelMapperConvertException: Unable to convert "2958465" from [L:1]:[C:1] to System.DateTime.
 ---> System.InvalidCastException: Invalid cast from 'Double' to 'DateTime'.
   at System.Double.System.IConvertible.ToDateTime(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Ganss.Excel.ColumnInfo.GetPropertyValue(Object o, Object val, ICell cell)
   at Ganss.Excel.ColumnInfo.SetProperty(Object o, Object val, ICell cell)
   at Ganss.Excel.ExcelMapper.MapCells(Type type, Func`3 valueParser, TypeMapper typeMapper, IEnumerable`1 cells, Int32& objInstanceIdx, IRow row, ISet`1 callChain)
   --- End of inner exception stack trace ---
   at Ganss.Excel.ExcelMapper.TriggerOrThrowParsingError(ExcelMapperConvertException excelMapperConvertException)
   at Ganss.Excel.ExcelMapper.MapCells(Type type, Func`3 valueParser, TypeMapper typeMapper, IEnumerable`1 cells, Int32& objInstanceIdx, IRow row, ISet`1 callChain)
   at Ganss.Excel.ExcelMapper.Fetch(ISheet sheet, Type type, Func`3 valueParser)+MoveNext()
```

There is no parsing error if I change the date to 30/12/9999. Is this a bug or a limitation?

**Comment by mganss** [comment]
This was a bug. Fixed in 5.2.471. Thanks for reporting.
